### ISSUE TITLE
Switch locale from ja_JP to ja

### ISSUE THREAD

**Issue by bess** [pulibrary/openpublishing#59]
Our CI for the ansible build for this service started failing in March 2023 because upstream OJS changed their locale names. Japanese is now "ja" instead of "ja_JP". 

See this issue for details: https://github.com/pkp/pkp-lib/issues/8598

When we upgrade we'll need to:
- [ ] Change the locale specified in our local Japanese translation
- [ ] Update the ansible role to copy that file to the correct location 
- [ ] Update the ansible role to point to the latest version of the translations (we are going to pin it to an older version in order to fix the CI build)

**Comment by bess** [comment]
This is the stanza we'll need to upgrade in ansible:

```

- name: ojs | clone translation repository
  ansible.builtin.git:
    repo: 'https://github.com/pkp/pkp-lib.git'
    dest: /opt/pkp-lib
    version: '3_3_0-14'
```
